baseURL: https://conflictednerd.github.io/
languageCode: en-us
title: Conflicting Ideas
theme: "PaperMod"

enableEmoji: true
paginate: 5

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Blog
                  url: blog
                  weight: 6
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Search
                  url: search/
                  weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON


params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Saeed's Personal Blog"
    author: Saeed Hedayatian
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    # images: ["p1.jpg"]

    profileMode:
        enabled: true
        title: A Collection of Conflicting Ideas
        subtitle: >
            Welcome to my blog 👋🏼


            I am Saeed Hedayatian. Currently, a computer science undergrad at Sharif University of Technology, Tehran.
            This blog is where I share intereting opinions, ideas, notes, etc. Mainly et cetera.
        imageUrl: "profile.jpg"
        imageTitle: profile photo
        imageWidth: 227
        imageHeight: 235
        buttons:
            - name: Archives
              url: archives
            - name: Categories
              url: categories
            - name: Blog
              url: blog
    homeInfoParams:
        Title: "A Collection of Conflicting Ideas"
        Content: >
            Welcome to my blog 👋🏼.

            - I am Saeed Hedayatian. Currently, a computer science undergrad at Sharif University of Technology, Tehran.

            - This blog is where I share intereting opinions, ideas, notes, etc. Mainly et cetera.
    socialIcons:
        - name: github
          url: "https://github.com/conflictednerd/"
        - name: twitter
          url: "https://twitter.com/HedayatianSaeed"
        - name: instagram
          url: "https://instagram.com/saeed_hedayatian"
        - name: telegram
          url: "https://t.me/mainlyetc"
        - name: email
          url: "mailto:hedayatians@gmail.com"
        # - name: Rss
        #   url: "index.xml"

    label:
        text: "Home"
        # icon: home.png
        iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        disableFingerprinting: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true